### ISSUE TITLE
Changes required for stacks?

### ISSUE THREAD

**Issue by schplat** [rackspace-cookbooks/contributing#16]
As we move to the new model, I think a lot of things here are changing.  Contributing.md probably requires a hefty rewrite, especially as we move to community.

**Comment by martinb3** [comment]
Committed some changes for stacks, https://github.com/rackspace-cookbooks/contributing/commit/cef159dc02fc17660a74e00fe2f21fe6ebc022dc.

**Comment by martinb3** [comment]
Introduced two new projects --
https://github.com/AutomationSupport/templatestack/
https://github.com/AutomationSupport/foodcritic-rackspace-rules/

Additional foodcritic rules will be used to check / enforce any possible standards. Templatestack will be a stack that can be copied as a base for new projects, will incorporate the gem for the additional foodcritic rules, and will also ship many other standard files.

**Comment by martinb3** [comment]
Please review https://github.com/AutomationSupport/templatestack, specifically:

https://github.com/AutomationSupport/templatestack/blob/master/README.md
https://github.com/AutomationSupport/templatestack/blob/master/CONTRIBUTING.md

I've defined foodcritic rules as a gem for us, as well as default files for most tools.
